name: Python package

on:
  push:
    tags:
      - 'v*.*.*'   # triggers when you push a version tag like v0.1.0
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build --wheel --sdist

    - name: Check package contents
      run: ls dist

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package locally
      run: |
        python -m pip install --upgrade pip
        pip install dist/*.whl

    - name: Run a quick test
      run: |
        python -c "from degradado import gradient, ansirgb; print(gradient(text='Test ok', mode="line-vertical", start_color=[0,0,0], end_color=[255,255,255])"
